export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_FAILURE = 'FETCH_BOOKS_FAILURE';
export const FETCH_BOOKS_REQUEST = 'FETCH_BOOKS_REQUEST';
export const ADD_BOOKS_REQUEST = 'ADD_BOOKS_REQUEST';
export const ADD_BOOKS_SUCCESS = 'ADD_BOOKS_SUCCESS';
export const CREATE_BOOK = 'CREATE_BOOK';
export const REMOVE_BOOK = 'REMOVE_BOOK';
